---
title: "inpatient_visits"
author: "Hershel Mehta"
date: "February 11, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dbplyr)
library(DBI)
library(RMySQL)
library(stringr)
```

## R Markdown

# Setup Data

## Setup connection to stride7

```{r}
con <- dbConnect(
    drv = RMySQL::MySQL(),
    dbname = "stride7",
    host = "shahlab-db1.stanford.edu",
    username = "hershelm",
    password = "EXMbP5M1gjqM")
```

## Setup tables from stride7

```{r}
SHC_visit_de <- tbl(con, "SHC_visit_de")
```

```{r}
SHC_visit_de %>% 
  head()
```

```{r}
demographics <- tbl(con, "demographics")
```

```{r}
demographics %>% 
  head()
```

```{r}
visits <- 
  SHC_visit_de %>% 
  select(patient_id, visit_id, contact_date, age_at_inp_adm_date_in_days) %>% 
  inner_join(
    demographics %>% 
      select(patient_id, birth_date),
    by = "patient_id"
  ) %>% 
  collect()
```

```{r}
inpatient_visits <- 
  visits %>% 
  filter(age_at_inp_adm_date_in_days > 0) 
```



```{r}
n_distinct(inpatient_visits$patient_id)
```

102283 patients with inpatient status
